version: '3.1'

services:
  php:
    build: 
      context: ./php
    # volumes:
    #   - ./www/public:/var/www
    # restart: always  
    ports:
      - "8082:80"
   
  
  db:
    image: mariadb:10.6
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass111

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
